"""Bake shared-rig crossbow grip poses with the existing anatomical hand IK.

The output is local animation-track quaternions, including each bone's rest frame.
Both palms meet the weapon, its long axis points forward, and the prod stays level.
Run with Python/numpy; no Blender installation or character GLB rebuild is needed.
"""
import json
from pathlib import Path
import numpy as np
from bh_anim import Rig, DEFAULTS, Anim
from bh_skeleton import STD, PARENT, BONE_ORDER
from bh_math import mat_to_quat
from lib_poses import U, RELAX, feet, hips, torso, grip, two_hand, look

ROOT=Path(__file__).resolve().parents[3]
rig=Rig(STD)
base=U(RELAX,feet(.13,-.12,.13,.14,7,15),hips(0,0,-.04),torso(),look())
poses={}
channels_by_name={}
def bake(channels):
    q,translation,global_pose=rig.evaluate(channels)
    rotations={}
    for bone in BONE_ORDER[1:]:
        local=rig.R0[PARENT[bone]].T @ q[bone] @ rig.R0[bone]
        w,x,y,z=mat_to_quat(local)
        rotations[bone]=[round(float(x),8),round(float(y),8),round(float(z),8),round(float(w),8)]
    return {"rotations":rotations,"hips_position":[0.0,STD['pelvis_h']+float(translation[2]),0.0]},global_pose
for name,height,pitch,forward,support in [
    ('ready',1.25,-8,.24,.20),
    ('aim',1.39,0,.26,.20),
    ('recoil',1.405,2,.23,.20),
    ('reload',1.29,-7,.24,.09),
]:
    channels=U(DEFAULTS,base,grip('R',12,forward,height,0,pitch,-90,pole=10,free=0),two_hand('L',support,0,pole=-15))
    channels['hik.R.rollauto']=0
    channels_by_name[name]=channels
    poses[name],global_pose=bake(channels)
    socket=global_pose['weapon.R']
    muzzle=socket.R @ rig.R0['weapon.R'][:,1]
    main=socket.apply(rig.h['weapon.R'])
    off=global_pose['weapon.L'].apply(rig.h['weapon.L'])
    error=float(np.linalg.norm(off-(main+muzzle*support)))
    print(name,'muzzle',muzzle.round(3),'support_error_m',round(error,4))
    assert error < .025
shots={}
for name,duration,release in [('fire',.85,.12),('heavy',1.,.2)]:
    animation=Anim(name,60)
    times=[0,release,release+.07,duration*.45,duration*.65,duration*.86,duration]
    for time,pose in zip(times,['ready','aim','recoil','aim','reload','reload','ready']):
        animation.key(time/duration*60,channels_by_name[pose])
    rig.warm={}
    frames=[]
    for i in range(61):
        frame,_=bake(animation.channels(i))
        frames.append(frame)
    shots[name]={'times':[round(i*duration/60,8) for i in range(61)],'frames':frames}
    rig.warm=None
text='extends RefCounted\n## Generated by tools/blender/characters/crossbow_poses.py with anatomical two-hand IK.\nconst POSES := '+json.dumps(poses,indent=2)+'\nconst SHOTS := '+json.dumps(shots,separators=(',',':'))+'\n'
(ROOT/'game/src/actors/crossbow_pose_data.gd').write_text(text,encoding='utf-8')
