"""Authoritative catalog for the fifty hand-designed weapon additions.

Run with system Python to regenerate DataArtisanWeapons and the asset manifest.
Geometry is in artisan_weapons.py; index is a design, never a palette swap.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
NAMES = {
    "bow": ["Heron Wing Bow", "Antler Crown Bow", "Serpent Coil Bow", "Sunwheel Bow", "Ironleaf Bow", "Twin Crescent Bow", "Dragon Rib Bow", "Tide Harp Bow", "Crystal Spire Bow", "Clockwork Cam Bow"],
    "crossbow": ["Ashwood Crossbow", "Crane Lever Crossbow", "Iron Boar Crossbow", "Twin Rail Crossbow", "Repeater Crossbow", "Raven Wing Crossbow", "Sun Dial Crossbow", "Frost Fork Crossbow", "Dragon Jaw Crossbow", "Orrery Crossbow"],
    "dagger": ["Gull Hook Dagger", "Scorpion Tail Dagger", "Glass Leaf Dagger", "Trident Dirk", "Crescent Fang Dagger", "Serpent Kris Dagger", "Sawback Dagger", "Orchid Fan Dagger", "Twin Fang Dagger", "Star Compass Dagger"],
    "sword": ["Heron Estoc", "Harbor Basket Sword", "Copperleaf Sword", "Flame Ribbon Sword", "Moon Hook Sword", "Split Crown Sword", "Dragon Tooth Sword", "Tide Scimitar", "Prism Greatblade", "Astral Ring Sword"],
    "axe": ["Raven Beak Axe", "Anchor Beard Axe", "Crescent Moon Axe", "Boar Cleaver Axe", "Twin Petal Axe", "Dragon Talon Axe", "Sun Disc Axe", "Frost Pick Axe", "Gothic Window Axe", "Thunder Fork Axe"],
}
DETAILS = {
    "bow": ["Swept feather-shaped limbs and a pierced riser", "Branching antler tips and bone lamination", "An asymmetric spiral limb with serpent fangs", "A wheel-centered riser and broad sun-ray limbs", "Overlapping leaf plates on reinforced limbs", "Twin open crescent frames and silver inlay", "Ribbed dragon wings and hooked horn tips", "A flowing double limb with harp-like braces", "Faceted crystal forks over a steel skeleton", "Large eccentric cams with split limbs and cables"],
    "crossbow": ["A carved ash stock, steel prod and open stirrup", "A long crane lever and narrow recurved prod", "A broad plated stock with tusk-shaped limbs", "Two exposed bolt rails and a split nose", "A five-bolt magazine and loading lever", "Swept feather blades and a hollow shoulder stock", "A sunwheel crank with radial brass spokes", "Pronged ice limbs and a forked muzzle", "A dragon-jaw stirrup with teeth and rib armor", "Concentric aiming rings and geared compound limbs"],
    "dagger": ["A hooked single edge and beak-shaped guard", "A recurved point with a tail-ring pommel", "A wide leaf blade with a faceted crystal core", "Three distinct points and an open trident guard", "A deep crescent cutting edge and hooked hilt", "A five-wave blade with twin serpent guards", "A broad clip point with pronounced saw teeth", "A petal-shaped blade and fan guard", "Two open-separated fangs on a common tang", "A star guard, hollow compass pommel and needle blade"],
    "sword": ["A narrow thrusting blade with feather crossguard", "A curved cutlass with a closed basket guard", "A broad leaf blade and branching copper hilt", "A wide flamberge with a swept flame guard", "A forward-hooked blade with a moon guard", "A split terminal crown and angular crossguard", "A serrated spine with a dragon-mouth guard", "A strongly swept blade with a wave knuckle guard", "A broad faceted blade and crystal quillons", "A ring-guard blade with an open celestial pommel"],
    "axe": ["A narrow hooked beak and rear pick", "A deep anchor-shaped beard and wrapped haft", "A wide hollow crescent and silver edge", "A broad square cleaver with tusk lugs", "Twin petal blades with open negative space", "Three curved claw blades around a reinforced socket", "A round sun blade with radial teeth", "A long ice pick and a small counterweight blade", "A pierced arch head with a broad sharpened edge", "A forked lightning head and angular haft braces"],
}
ELEMENTS = [0, 0, 4, 1, 0, 8, 7, 6, 2, 3]
LEVELS = [1, 5, 10, 16, 22, 29, 36, 43, 51, 59]

def rows():
    out = []
    for family, names in NAMES.items():
        for i, name in enumerate(names):
            iid = name.lower().replace(" ", "_")
            if family != "crossbow":
                iid = "artisan_" + iid
            aps = {"bow": 1.15, "crossbow": .82, "dagger": 2.05, "sword": 1.48, "axe": 1.20}[family] * [1, 1.06, .94, 1.02, .90, 1.08, .96, 1.04, .88, 1][i]
            out.append(dict(id=iid, name=name, weapon_type=family, design=i, level=LEVELS[i], aps=round(aps, 3), element=ELEMENTS[i], element_share=.2 if ELEMENTS[i] else 0, category="weapon", description=DETAILS[family][i]))
    return out

def main():
    data = rows()
    (HERE / "artisan_manifest.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    values = [[r[k] for k in ["id", "name", "weapon_type", "level", "aps", "element", "description"]] for r in data]
    code = 'class_name DataArtisanWeapons\n## Generated by tools/blender/items/artisan_catalog.py. Ten distinct designs per family.\nconst ROWS := [\n' + ',\n'.join('\t' + json.dumps(r) for r in values) + '\n]\n'
    code += '''
static func bases() -> Array:
	var out := []
	for r in ROWS:
		var family := StringName(r[2])
		var level := int(r[3])
		var damage := DataItems.roster_damage(family, level, float(r[4]))
		var attribute: StringName = &"str" if family in [&"sword", &"axe"] else &"dex"
		var b := DataItems._b(StringName(r[0]), r[1], &"weapon", "", {
			"weapon_type": family, "level_req": level, "drop_level": level,
			"requirements": {attribute: 9 + level}, "damage_min": damage.x, "damage_max": damage.y,
			"attacks_per_second": float(r[4]), "value": 18 + level * 5,
			"class_hint": DataItems._weapon_class(family), "tier": mini(3, 1 + level / 18),
			"element": int(r[5]), "element_share": 0.2 if int(r[5]) != 0 else 0.0,
			"flavor": r[6] + "."})
		b.icon = DataItems.ICON3D % b.id
		b.model = ItemBaseDef.ITEM_MODEL % b.id
		# The different stocks, guards and limb assemblies carry different mass.
		b.weight += [0.03, 0.09, 0.17, 0.23, 0.31, 0.39, 0.47, 0.53, 0.61, 0.69][out.size() % 10]
		out.append(b)
	return out
'''
    (ROOT / "game/src/data/data_items_artisan.gd").write_text(code, encoding="utf-8")
    print(f"Wrote {len(data)} distinct weapon designs")

if __name__ == "__main__":
    main()
