class_name DataArtisanWeapons
## Generated by tools/blender/items/artisan_catalog.py. Ten distinct designs per family.
const ROWS := [
	["artisan_heron_wing_bow", "Heron Wing Bow", "bow", 1, 1.15, 0, "Swept feather-shaped limbs and a pierced riser"],
	["artisan_antler_crown_bow", "Antler Crown Bow", "bow", 5, 1.219, 0, "Branching antler tips and bone lamination"],
	["artisan_serpent_coil_bow", "Serpent Coil Bow", "bow", 10, 1.081, 4, "An asymmetric spiral limb with serpent fangs"],
	["artisan_sunwheel_bow", "Sunwheel Bow", "bow", 16, 1.173, 1, "A wheel-centered riser and broad sun-ray limbs"],
	["artisan_ironleaf_bow", "Ironleaf Bow", "bow", 22, 1.035, 0, "Overlapping leaf plates on reinforced limbs"],
	["artisan_twin_crescent_bow", "Twin Crescent Bow", "bow", 29, 1.242, 8, "Twin open crescent frames and silver inlay"],
	["artisan_dragon_rib_bow", "Dragon Rib Bow", "bow", 36, 1.104, 7, "Ribbed dragon wings and hooked horn tips"],
	["artisan_tide_harp_bow", "Tide Harp Bow", "bow", 43, 1.196, 6, "A flowing double limb with harp-like braces"],
	["artisan_crystal_spire_bow", "Crystal Spire Bow", "bow", 51, 1.012, 2, "Faceted crystal forks over a steel skeleton"],
	["artisan_clockwork_cam_bow", "Clockwork Cam Bow", "bow", 59, 1.15, 3, "Large eccentric cams with split limbs and cables"],
	["ashwood_crossbow", "Ashwood Crossbow", "crossbow", 1, 0.82, 0, "A carved ash stock, steel prod and open stirrup"],
	["crane_lever_crossbow", "Crane Lever Crossbow", "crossbow", 5, 0.869, 0, "A long crane lever and narrow recurved prod"],
	["iron_boar_crossbow", "Iron Boar Crossbow", "crossbow", 10, 0.771, 4, "A broad plated stock with tusk-shaped limbs"],
	["twin_rail_crossbow", "Twin Rail Crossbow", "crossbow", 16, 0.836, 1, "Two exposed bolt rails and a split nose"],
	["repeater_crossbow", "Repeater Crossbow", "crossbow", 22, 0.738, 0, "A five-bolt magazine and loading lever"],
	["raven_wing_crossbow", "Raven Wing Crossbow", "crossbow", 29, 0.886, 8, "Swept feather blades and a hollow shoulder stock"],
	["sun_dial_crossbow", "Sun Dial Crossbow", "crossbow", 36, 0.787, 7, "A sunwheel crank with radial brass spokes"],
	["frost_fork_crossbow", "Frost Fork Crossbow", "crossbow", 43, 0.853, 6, "Pronged ice limbs and a forked muzzle"],
	["dragon_jaw_crossbow", "Dragon Jaw Crossbow", "crossbow", 51, 0.722, 2, "A dragon-jaw stirrup with teeth and rib armor"],
	["orrery_crossbow", "Orrery Crossbow", "crossbow", 59, 0.82, 3, "Concentric aiming rings and geared compound limbs"],
	["artisan_gull_hook_dagger", "Gull Hook Dagger", "dagger", 1, 2.05, 0, "A hooked single edge and beak-shaped guard"],
	["artisan_scorpion_tail_dagger", "Scorpion Tail Dagger", "dagger", 5, 2.173, 0, "A recurved point with a tail-ring pommel"],
	["artisan_glass_leaf_dagger", "Glass Leaf Dagger", "dagger", 10, 1.927, 4, "A wide leaf blade with a faceted crystal core"],
	["artisan_trident_dirk", "Trident Dirk", "dagger", 16, 2.091, 1, "Three distinct points and an open trident guard"],
	["artisan_crescent_fang_dagger", "Crescent Fang Dagger", "dagger", 22, 1.845, 0, "A deep crescent cutting edge and hooked hilt"],
	["artisan_serpent_kris_dagger", "Serpent Kris Dagger", "dagger", 29, 2.214, 8, "A five-wave blade with twin serpent guards"],
	["artisan_sawback_dagger", "Sawback Dagger", "dagger", 36, 1.968, 7, "A broad clip point with pronounced saw teeth"],
	["artisan_orchid_fan_dagger", "Orchid Fan Dagger", "dagger", 43, 2.132, 6, "A petal-shaped blade and fan guard"],
	["artisan_twin_fang_dagger", "Twin Fang Dagger", "dagger", 51, 1.804, 2, "Two open-separated fangs on a common tang"],
	["artisan_star_compass_dagger", "Star Compass Dagger", "dagger", 59, 2.05, 3, "A star guard, hollow compass pommel and needle blade"],
	["artisan_heron_estoc", "Heron Estoc", "sword", 1, 1.48, 0, "A narrow thrusting blade with feather crossguard"],
	["artisan_harbor_basket_sword", "Harbor Basket Sword", "sword", 5, 1.569, 0, "A curved cutlass with a closed basket guard"],
	["artisan_copperleaf_sword", "Copperleaf Sword", "sword", 10, 1.391, 4, "A broad leaf blade and branching copper hilt"],
	["artisan_flame_ribbon_sword", "Flame Ribbon Sword", "sword", 16, 1.51, 1, "A wide flamberge with a swept flame guard"],
	["artisan_moon_hook_sword", "Moon Hook Sword", "sword", 22, 1.332, 0, "A forward-hooked blade with a moon guard"],
	["artisan_split_crown_sword", "Split Crown Sword", "sword", 29, 1.598, 8, "A split terminal crown and angular crossguard"],
	["artisan_dragon_tooth_sword", "Dragon Tooth Sword", "sword", 36, 1.421, 7, "A serrated spine with a dragon-mouth guard"],
	["artisan_tide_scimitar", "Tide Scimitar", "sword", 43, 1.539, 6, "A strongly swept blade with a wave knuckle guard"],
	["artisan_prism_greatblade", "Prism Greatblade", "sword", 51, 1.302, 2, "A broad faceted blade and crystal quillons"],
	["artisan_astral_ring_sword", "Astral Ring Sword", "sword", 59, 1.48, 3, "A ring-guard blade with an open celestial pommel"],
	["artisan_raven_beak_axe", "Raven Beak Axe", "axe", 1, 1.2, 0, "A narrow hooked beak and rear pick"],
	["artisan_anchor_beard_axe", "Anchor Beard Axe", "axe", 5, 1.272, 0, "A deep anchor-shaped beard and wrapped haft"],
	["artisan_crescent_moon_axe", "Crescent Moon Axe", "axe", 10, 1.128, 4, "A wide hollow crescent and silver edge"],
	["artisan_boar_cleaver_axe", "Boar Cleaver Axe", "axe", 16, 1.224, 1, "A broad square cleaver with tusk lugs"],
	["artisan_twin_petal_axe", "Twin Petal Axe", "axe", 22, 1.08, 0, "Twin petal blades with open negative space"],
	["artisan_dragon_talon_axe", "Dragon Talon Axe", "axe", 29, 1.296, 8, "Three curved claw blades around a reinforced socket"],
	["artisan_sun_disc_axe", "Sun Disc Axe", "axe", 36, 1.152, 7, "A round sun blade with radial teeth"],
	["artisan_frost_pick_axe", "Frost Pick Axe", "axe", 43, 1.248, 6, "A long ice pick and a small counterweight blade"],
	["artisan_gothic_window_axe", "Gothic Window Axe", "axe", 51, 1.056, 2, "A pierced arch head with a broad sharpened edge"],
	["artisan_thunder_fork_axe", "Thunder Fork Axe", "axe", 59, 1.2, 3, "A forked lightning head and angular haft braces"]
]

static func bases() -> Array:
	var out := []
	for r in ROWS:
		var family := StringName(r[2])
		var level := int(r[3])
		var damage := DataItems.roster_damage(family, level, float(r[4]))
		var attribute: StringName = &"str" if family in [&"sword", &"axe"] else &"dex"
		var b := DataItems._b(StringName(r[0]), r[1], &"weapon", "", {
			"weapon_type": family, "level_req": level, "drop_level": level,
			"requirements": {attribute: 9 + level}, "damage_min": damage.x, "damage_max": damage.y,
			"attacks_per_second": float(r[4]), "value": 18 + level * 5,
			"class_hint": DataItems._weapon_class(family), "tier": mini(3, 1 + level / 18),
			"element": int(r[5]), "element_share": 0.2 if int(r[5]) != 0 else 0.0,
			"flavor": r[6] + "."})
		b.icon = DataItems.ICON3D % b.id
		b.model = ItemBaseDef.ITEM_MODEL % b.id
		# The different stocks, guards and limb assemblies carry different mass.
		b.weight += [0.03, 0.09, 0.17, 0.23, 0.31, 0.39, 0.47, 0.53, 0.61, 0.69][out.size() % 10]
		out.append(b)
	return out
