"""bh-033: write docs/ASSET_SOURCES.md from assets_src/bh033/sources.json (the download records of the Poly Haven props and
Quaternius creatures), listing each downloaded model once with its authors, licence, page and runtime file.

    python tools/bh033_asset_sources.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = json.load(open(ROOT / "assets_src/bh033/sources.json", encoding="utf-8"))
ENV = ROOT / "game/assets/environment"
SWAPS = {"Ghost_Skull": "gloomwraith_q.scn (Gloomwraith)", "Wasp": "hive_drone_q.scn (Hive Drone)", "Mushnub": "sporeling_q.scn (Sporeling)"}

models = {}
for r in SRC:
    key = (r.get("source", ""), r.get("model") or Path(r.get("path", "")).stem)
    m = models.setdefault(key, {"files": 0, "bytes": 0})
    m["files"] += 1
    m["bytes"] += int(r.get("bytes", 0))
    for k in ("name", "authors", "license", "page", "url", "pack", "author"):
        if r.get(k) and k not in m:
            m[k] = r[k]

lines = ["# Downloaded asset sources (bh-033)", "",
         "Generated by `tools/bh033_asset_sources.py` from `assets_src/bh033/sources.json` (every file's URL, size, SHA-256 and",
         "download date are there). Originals stay in `assets_src/bh033/`; only the runtime copies named below ship in the game.",
         "The map-design pass's Kenney models are listed in `ASSET_CREDITS_MAP_DESIGN.md`.", "",
         "| Source | Model | Authors | Licence | Page | In the game |", "| --- | --- | --- | --- | --- | --- |"]
for (src, model), m in sorted(models.items()):
    runtime = ""
    if src == "Poly Haven":
        stem = "ph_" + model.lower()
        runtime = f"`assets/environment/{stem}.glb`" if (ENV / f"{stem}.glb").exists() else "not used"
    elif model in SWAPS:
        runtime = f"`assets/characters/bh033/{SWAPS[model]}`"
    else:
        runtime = "not used"
    authors = ", ".join(m.get("authors", [])) if isinstance(m.get("authors"), list) else str(m.get("authors", m.get("author", "")))
    if not authors and src in ("Quaternius", "Kenney"):
        authors = src
    lines.append(f"| {src} | {m.get('name', model)} | {authors or '—'} | {m.get('license', '—')} | {m.get('page', m.get('url', '—'))} | {runtime} |")
lines.append("")
(ROOT / "docs/ASSET_SOURCES.md").write_text("\n".join(lines), encoding="utf-8")
print(len(models), "models")
