"""Map-design pass (2026-10-03): accepted / deferred / rejected inventory of the downloaded Kenney sources, with where
each prepared piece is actually used in the game.

    python tools/map_design_inventory.py

Reads work/map-design/prepared/index.json (preparation receipts), work/map-design/scratch/build_all.json and
rooms_all.json (written by tests/tools/map_design_probe.tscn --cmd=build / --cmd=rooms over every map and floor) and
game/src/data/data_dungeon_roles.gd (motif -> pieces). Writes output/map-design-20261003/assets/accepted_assets.{json,md}
and ASSET_CREDITS_MAP_DESIGN.md. Nothing is guessed: a piece counts as used only where a build placed it.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIB = ROOT / "assets_src/map_design_20261003"
OUT = ROOT / "output/map-design-20261003/assets"


def motif_pieces():
    src = (ROOT / "game/src/data/data_dungeon_roles.gd").read_text(encoding="utf-8")
    body = src[src.index("const M := {"):src.index("const T := {")]
    out = {}
    for m in re.finditer(r'^\t"(\w+)": \{(.*?)\]\]\},?\s*$', body, re.S | re.M):
        out[m.group(1)] = sorted(set(re.findall(r'\["(kd_\w+|[a-z_]+)"', m.group(2))))
    # boss silhouettes are recorded as "boss:<piece>"
    return out


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = {a["id"]: a for a in json.load(open(LIB / "manifest.json"))["assets"]}
    index = json.load(open(ROOT / "work/map-design/prepared/index.json"))
    built = json.load(open(ROOT / "work/map-design/scratch/build_all.json"))
    rooms = json.load(open(ROOT / "work/map-design/scratch/rooms_all.json"))
    motifs = motif_pieces()
    used = {}
    for mid, v in built.items():
        for piece in v["census"]["kd"]:
            used.setdefault(piece, set()).add(mid)
    for fid, v in rooms.items():
        for g in v["groups"]:
            role, names = g.split(":", 1)
            for mname in [n for n in names.split(",") if n]:
                if mname.startswith("boss:") or mname.startswith("boss"):
                    continue
                for piece in motifs.get(mname, []):
                    if piece.startswith("kd_"):
                        used.setdefault(piece, set()).add("dungeon:" + v["theme"])
            for b in re.findall(r"boss:(kd_\w+)", names):
                used.setdefault(b, set()).add("dungeon:" + v["theme"])
    rows = []
    for sid, a in manifest.items():
        key = sid.replace("kenney_", "")
        rec = index["accepted"].get(key)
        if rec:
            name = rec["runtime"].split("/")[-1][:-4]
            where = sorted(used.get(name, []))
            rows.append({"number": a["number"], "source": sid, "kit": a["kit"], "decision": "accepted" if where else "accepted (unplaced)",
                         "runtime": name, "used_in": where, "triangles": rec["triangles"], "surfaces": rec["surfaces"],
                         "materials": rec["materials"], "scale": rec["scale"], "bounds_m": rec["bounds_m"], "collision": rec["collision"],
                         "source_sha256": rec["source_sha256"], "derived_sha256": rec["derived_sha256"], "package": a["package"]})
        else:
            reason = index["deferred"].get(key, "not considered")
            rows.append({"number": a["number"], "source": sid, "kit": a["kit"], "decision": reason.split(":")[0],
                         "reason": reason.split(":", 1)[1].strip() if ":" in reason else reason, "package": a["package"]})
    rows.sort(key=lambda r: r["number"])
    (OUT / "accepted_assets.json").write_text(json.dumps(rows, indent=1))
    placed = [r for r in rows if r["decision"] == "accepted"]
    md = ["# Map-design asset inventory (generated)", "",
          f"{len(rows)} downloaded source models considered: **{len(placed)} placed in the game**, "
          f"{sum(1 for r in rows if r['decision'] == 'accepted (unplaced)')} prepared but unplaced, "
          f"{sum(1 for r in rows if r['decision'] in ('deferred', 'rejected'))} deferred or rejected.", "",
          "Generated by `tools/map_design_inventory.py` from the preparation receipts and real map builds.", "",
          "| # | Source model | Decision | Runtime piece | Used in | Tris | Surfaces | Materials |",
          "| ---: | --- | --- | --- | --- | ---: | ---: | --- |"]
    for r in rows:
        if r["decision"].startswith("accepted"):
            where = ", ".join(r["used_in"][:6]) + (" …" if len(r["used_in"]) > 6 else "")
            md.append(f"| {r['number']} | {r['source']} | {r['decision']} | `{r['runtime']}` | {where} | {r['triangles']} | {r['surfaces']} | {', '.join(r['materials'])} |")
        else:
            md.append(f"| {r['number']} | {r['source']} | {r['decision']} | — | {r['reason']} | | | |")
    (OUT / "accepted_assets.md").write_text("\n".join(md) + "\n", encoding="utf-8")

    kits = {}
    for r in placed:
        kits[r["kit"]] = kits.get(r["kit"], 0) + 1
    credits = ["# Downloaded map design source credits", "",
               "Downloaded and curated 3 October 2026; integrated in the map-design pass the same day. All five packs are by",
               "[Kenney](https://kenney.nl) and licensed [CC0-1.0](https://creativecommons.org/publicdomain/zero/1.0/); creator credit is",
               "kept here although CC0 does not require it. Original licenses: `assets_src/map_design_20261003/licenses/`.", "",
               "| Pack | Source | License | Models curated | Placed in the game |", "| --- | --- | --- | ---: | ---: |"]
    for kit, url, n in [("nature-kit", "https://kenney.nl/assets/nature-kit", 48), ("furniture-kit", "https://kenney.nl/assets/furniture-kit", 26),
                        ("pirate-kit", "https://kenney.nl/assets/pirate-kit", 20), ("graveyard-kit", "https://kenney.nl/assets/graveyard-kit", 16),
                        ("modular-dungeon-kit", "https://kenney.nl/assets/modular-dungeon-kit", 4)]:
        credits.append(f"| {kit} | {url} | CC0-1.0 | {n} | {kits.get(kit, 0)} |")
    credits += ["", "## What was done to them", "",
                "`tools/blender/environment/prepare_kenney.py` (Blender 5.2) reads each accepted canonical package (unchanged) and writes",
                "`game/assets/environment/kd_<name>.glb`: every part joined into one mesh with its node transform applied, scaled to game",
                "metres, seated on its origin, front +Z; animations, armatures and skins dropped; each part's material renamed to the game's",
                "shared material set (flat-colour parts by source material name, palette-textured parts per face by the palette colour",
                "under the face), so the game's own lit, textured materials replace the source colours. Simple box collision is added to",
                "furniture, large rocks and tree trunks. Per-model receipts with source and derived SHA-256: `work/map-design/prepared/`.",
                "Canonical packages were verified and admitted with the game-dev tool into `game/assets/vendor/` (ignored by Godot, not",
                "exported); lock file: `game/.game-dev/vendor-lock.json`.", "",
                "## Not used", "", "| Source model | Decision | Reason |", "| --- | --- | --- |"]
    for r in rows:
        if not r["decision"].startswith("accepted"):
            credits.append(f"| {r['source']} | {r['decision']} | {r['reason']} |")
    for r in rows:
        if r["decision"] == "accepted (unplaced)":
            credits.append(f"| {r['source']} | prepared, not placed | no map needed it in this pass |")
    credits += ["", f"The full per-model inventory with where each piece is used: `output/map-design-20261003/assets/accepted_assets.md`.", ""]
    (ROOT / "ASSET_CREDITS_MAP_DESIGN.md").write_text("\n".join(credits), encoding="utf-8")
    print(f"placed {len(placed)} / {len(rows)}; unplaced {[r['runtime'] for r in rows if r['decision'] == 'accepted (unplaced)']}")


if __name__ == "__main__":
    main()
